-- รันไฟล์นี้ใน Supabase Dashboard > SQL Editor
-- ตารางข้อมูลผู้ใช้ เชื่อมกับ Supabase Auth
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  student_number text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  subject text not null,
  due_date date not null,
  status text not null default 'pending' check (status in ('pending', 'progress', 'done')),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.assignments enable row level security;

create policy "อ่านโปรไฟล์ของตนเอง" on public.profiles for select using (auth.uid() = id);
create policy "แก้ไขโปรไฟล์ของตนเอง" on public.profiles for update using (auth.uid() = id);
create policy "เพิ่มโปรไฟล์ของตนเอง" on public.profiles for insert with check (auth.uid() = id);
create policy "จัดการงานของตนเอง" on public.assignments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger assignments_updated_at before update on public.assignments
for each row execute function public.set_updated_at();
